[package]
name = "matrixmultiply_mt"
version = "0.2.0"
authors = ["bluss", "J. Millard"]

license = "MIT/Apache-2.0"

repository = "https://github.com/millardjn/matrixmultiply"
documentation = "https://bluss.github.io/matrixmultiply/"

description = "Multithreaded Fork. General matrix multiplication of f32 and f64 matrices in Rust. Supports matrices with general strides. Uses a microkernel strategy, so that the implementation is easy to parallelize and optimize. `RUSTFLAGS=\"-C target-cpu=native\"` is your friend here."

keywords = ["matrix", "sgemm", "dgemm"]

[lib]
bench = false

[dependencies]
rawpointer = "0.1"
num_cpus = "0.2"
threadpool = "1.3"
lazy_static = "0.2"
typenum = "*"
typenum_loops = "0.1.1"
generic-array = {git = "https://github.com/millardjn/generic-array.git"} #"0.5"
num = "0.1"

