
array_width = 80
chain_one_line_max = 80
closure_block_indent_threshold = 1
control_style = "Legacy"
fn_brace_style = "PreferSameLine"
fn_call_width = 80
fn_single_line = true
hard_tabs = true
item_brace_style = "PreferSameLine"
match_block_trailing_comma = true
max_width = 120
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 60
struct_lit_width = 30
use_try_shorthand = true
wrap_comments = true